development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sebbo_development
  pool: 5
  username: root
  password: emiolo123456
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sebbo_test
  pool: 5
  username: root
  password: emiolo123456
  host: localhost

